version: 2
updates:
- package-ecosystem: docker
  directory: "/rubocop"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/eslint"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
